{
    "item1":{"asunto":"El Destino", "url":"https://youtu.be/_bEK7f_B1pM?t=1330"},
    "item2":{"asunto":"La Tierra", "url":"https://youtu.be/_bEK7f_B1pM?t=1485"},
    "item3":{"asunto":"El Hombre", "url":"https://youtu.be/_bEK7f_B1pM?t=1537"},
    "item4":{"asunto":"Urano", "url":"https://youtu.be/_bEK7f_B1pM?t=1690"},
    "item":{"asunto":"Saturno", "url":"https://youtu.be/_bEK7f_B1pM?t=1829"},
    "item":{"asunto":"Saturno Encarnado - Edad de Oro - Comunismo - Saturnales - Carnaval", "url":"https://youtu.be/_bEK7f_B1pM?t=1943"},
    "item":{"asunto":"Saturno - Cronos - Tiempo - Muerte", "url":"https://youtu.be/_bEK7f_B1pM?t=2089"},
    "item":{"asunto":"Saturno - Esposa Rea Cibeles- Hijos", "url":"https://youtu.be/_bEK7f_B1pM?t=2223"},
    "item":{"asunto":"Rea Cibeles", "url":"https://youtu.be/_bEK7f_B1pM?t=2249"},
    "item":{"asunto":"El Olimpo", "url":"https://youtu.be/_bEK7f_B1pM?t=2661"},
    "item":{"asunto":"Júpiter", "url":"https://youtu.be/_bEK7f_B1pM?t=2875"},
    "item":{"asunto":"Júpiter Vs Saturno - Rescate a sus hermanos", "url":"https://youtu.be/_bEK7f_B1pM?t=2965"},
    "item":{"asunto":"Júpiter - Esposas e Hijos", "url":"https://youtu.be/_bEK7f_B1pM?t=3237"},
    "item":{"asunto":"Juno traiciona a Jupiter - Olimpo", "url":"https://youtu.be/_bEK7f_B1pM?t=3265"},
    "item":{"asunto":"Culto a Júpiter - Como se lo conocía", "url":"https://youtu.be/_bEK7f_B1pM?t=3298"},
    "item":{"asunto":"Juno Hermana y Esposa de Júpiter", "url":"https://youtu.be/_bEK7f_B1pM?t=3529"},
    "item":{"asunto":"Minerva - Phalas - Athenea", "url":"https://youtu.be/_bEK7f_B1pM?t=3989"},
    "item":{"asunto":"Vesta - Hestia - Diosa del Fuego", "url":"https://youtu.be/_bEK7f_B1pM?t=4418"},
    "item":{"asunto":"Latona - Esposa de Júpiter - Madre de Apolo", "url":"https://youtu.be/_bEK7f_B1pM?t=4733"},
    "item":{"asunto":"Apolo - Febo - El Sol", "url":"https://youtu.be/_bEK7f_B1pM?t=4815"},
    "item":{"asunto":"Diana - Artemisa - La Luna", "url":"https://youtu.be/_bEK7f_B1pM?t=5423"},
    "item":{"asunto":"Ceres - Demeter - Hija de Saturno - Madre de Proserpina - Rapto de Hades Plutón a Proserpina", "url":"https://youtu.be/_bEK7f_B1pM?t=5903"},
    "item":{"asunto":"Vulcano - Hefesto - Hijo de Juno", "url":"https://youtu.be/_bEK7f_B1pM?t=6586"},
    "item":{"asunto":"Mercurio - Hermes - Hijo de Júpiter y Maia", "url":"https://youtu.be/_bEK7f_B1pM?t=6958"},
    "item":{"asunto":"Marte - Ares - Hijo de Júpiter y Juno", "url":"https://youtu.be/_bEK7f_B1pM?t=7593"},
    "item":{"asunto":"Venus  - Afrodita", "url":"https://youtu.be/_bEK7f_B1pM?t=8145"},
    "item":{"asunto":"Baco - Dionisio - Hijo de Júpiter y Sémele - El dios del vino", "url":"https://youtu.be/_bEK7f_B1pM?t=8887"},
    "item":{"asunto":"Temis - Hija del Cielo y la Tierra o de Urano y Titea - Hermana mayor de Saturno y tía de Júpiter - Diosa de la Justicia", "url":"https://youtu.be/_bEK7f_B1pM?t=9636"},
    "item":{"asunto":"Cupido o el Amor - Hijo de Venus y Marte", "url":"https://youtu.be/_bEK7f_B1pM?t=9766"},
    "item":{"asunto":"Iris - hija de Taumas y de Electra - Mensajera de los dioses", "url":"https://youtu.be/_bEK7f_B1pM?t=10146"},
    "item":{"asunto":"Hebe y Ganímedes - Hija de Júpiter y Juno", "url":"https://youtu.be/_bEK7f_B1pM?t=10243"},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""}
}
